
exports.seed = function(knex) {
  return knex('films').del()
    .then(function () {
      return knex('films').insert([
        {
          id: 1, 
          film_id: 1, 
          title: '', 
          director: '', 
          pub_date: '', 
          country: '', 
          description: '', 
          img: '', 
          tag_id: [], 
          forecast_id: []
        },
        {
          id: 2, 
          film_id: 2, 
          title: '', 
          director: '', 
          pub_date: '', 
          country: '', 
          description: '', 
          img: '', 
          tag_id: [], 
          forecast_id: []
        },
        {
          id: 3, 
          film_id: 3, 
          title: '', 
          director: '', 
          pub_date: '', 
          country: '', 
          description: '', 
          img: '', 
          tag_id: [], 
          forecast_id: []
        },
        {
          id: 4, 
          film_id: 4, 
          title: '', 
          director: '', 
          pub_date: '', 
          country: '', 
          description: '', 
          img: '', 
          tag_id: [], 
          forecast_id: []
        },
        {
          id: 5, 
          film_id: 5, 
          title: '', 
          director: '', 
          pub_date: '', 
          country: '', 
          description: '', 
          img: '', 
          tag_id: [], 
          forecast_id: []
        },
        {
          id: 6, 
          film_id: 6, 
          title: '', 
          director: '', 
          pub_date: '', 
          country: '', 
          description: '', 
          img: '', 
          tag_id: [], 
          forecast_id: []
        },
        {
          id: 7, 
          film_id: 7, 
          title: '', 
          director: '', 
          pub_date: '', 
          country: '', 
          description: '', 
          img: '', 
          tag_id: [], 
          forecast_id: []
        },
        {
          id: 8, 
          film_id: 8, 
          title: '', 
          director: '', 
          pub_date: '', 
          country: '', 
          description: '', 
          img: '', 
          tag_id: [], 
          forecast_id: []
        },
        {
          id: 9, 
          film_id: 9, 
          title: '', 
          director: '', 
          pub_date: '', 
          country: '', 
          description: '', 
          img: '', 
          tag_id: [], 
          forecast_id: []
        },
        {
          id: 10, 
          film_id: 10, 
          title: '', 
          director: '', 
          pub_date: '', 
          country: '', 
          description: '', 
          img: '', 
          tag_id: [], 
          forecast_id: []
        },
        {
          id: 11, 
          film_id: 11, 
          title: '', 
          director: '', 
          pub_date: '', 
          country: '', 
          description: '', 
          img: '', 
          tag_id: [], 
          forecast_id: []
        },
        {
          id: 12, 
          film_id: 12, 
          title: '', 
          director: '', 
          pub_date: '', 
          country: '', 
          description: '', 
          img: '', 
          tag_id: [], 
          forecast_id: []
        },
        {
          id: 13, 
          film_id: 13, 
          title: '', 
          director: '', 
          pub_date: '', 
          country: '', 
          description: '', 
          img: '', 
          tag_id: [], 
          forecast_id: []
        },
        {
          id: 14, 
          film_id: 14, 
          title: '', 
          director: '', 
          pub_date: '', 
          country: '', 
          description: '', 
          img: '', 
          tag_id: [], 
          forecast_id: []
        },
        {
          id: 15, 
          film_id: 15, 
          title: '', 
          director: '', 
          pub_date: '', 
          country: '', 
          description: '', 
          img: '', 
          tag_id: [], 
          forecast_id: []
        },
        {
          id: 16, 
          film_id: 16, 
          title: '', 
          director: '', 
          pub_date: '', 
          country: '', 
          description: '', 
          img: '', 
          tag_id: [], 
          forecast_id: []
        },
        {
          id: 17, 
          film_id: 17, 
          title: '', 
          director: '', 
          pub_date: '', 
          country: '', 
          description: '', 
          img: '', 
          tag_id: [], 
          forecast_id: []
        },
        {
          id: 18, 
          film_id: 18, 
          title: '', 
          director: '', 
          pub_date: '', 
          country: '', 
          description: '', 
          img: '', 
          tag_id: [], 
          forecast_id: []
        },
        {
          id: 19, 
          film_id: 19, 
          title: '', 
          director: '', 
          pub_date: '', 
          country: '', 
          description: '', 
          img: '', 
          tag_id: [], 
          forecast_id: []
        },
        {
          id: 20, 
          film_id: 20, 
          title: '', 
          director: '', 
          pub_date: '', 
          country: '', 
          description: '', 
          img: '', 
          tag_id: [], 
          forecast_id: []
        },
        {
          id: 21, 
          film_id: 21, 
          title: '', 
          director: '', 
          pub_date: '', 
          country: '', 
          description: '', 
          img: '', 
          tag_id: [], 
          forecast_id: []
        },
        {
          id: 22, 
          film_id: 22, 
          title: '', 
          director: '', 
          pub_date: '', 
          country: '', 
          description: '', 
          img: '', 
          tag_id: [], 
          forecast_id: []
        },
        {
          id: 23, 
          film_id: 23, 
          title: '', 
          director: '', 
          pub_date: '', 
          country: '', 
          description: '', 
          img: '', 
          tag_id: [], 
          forecast_id: []
        },
        {
          id: 24, 
          film_id: 24, 
          title: '', 
          director: '', 
          pub_date: '', 
          country: '', 
          description: '', 
          img: '', 
          tag_id: [], 
          forecast_id: []
        },
        {
          id: 25, 
          film_id: 25, 
          title: '', 
          director: '', 
          pub_date: '', 
          country: '', 
          description: '', 
          img: '', 
          tag_id: [], 
          forecast_id: []
        },
        {
          id: 26, 
          film_id: 26, 
          title: '', 
          director: '', 
          pub_date: '', 
          country: '', 
          description: '', 
          img: '', 
          tag_id: [], 
          forecast_id: []
        },
        {
          id: 27, 
          film_id: 27, 
          title: '', 
          director: '', 
          pub_date: '', 
          country: '', 
          description: '', 
          img: '', 
          tag_id: [], 
          forecast_id: []
        },
        {
          id: 28, 
          film_id: 28, 
          title: '', 
          director: '', 
          pub_date: '', 
          country: '', 
          description: '', 
          img: '', 
          tag_id: [], 
          forecast_id: []
        },
        {
          id: 29, 
          film_id: 29, 
          title: '', 
          director: '', 
          pub_date: '', 
          country: '', 
          description: '', 
          img: '', 
          tag_id: [], 
          forecast_id: []
        },
        {
          id: 30, 
          film_id: 30, 
          title: '', 
          director: '', 
          pub_date: '', 
          country: '', 
          description: '', 
          img: '', 
          tag_id: [], 
          forecast_id: []
        },
      ]);
    });
};
